trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Checkout code
- checkout: self

# Step 2: Debug step (optional)
- script: |
    echo "Repo structure:"
    ls -la
  displayName: "Debug: List files"

# Step 3: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# Step 4: Build React frontend
- script: |
    cd Frontend
    npm install
    npm run build
  displayName: 'Build React Frontend'

# Step 5: Install JDK 17
- task: JavaToolInstaller@0
  inputs:
    jdkSourceOption: 'PreInstalled'   # << obligatoire !
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
  displayName: 'Install JDK 17'


# Step 6: Build Spring Boot backend
- task: Maven@3
  inputs:
    mavenPomFile: 'Backend/pom.xml'
    goals: 'clean package -DskipTests'
    publishJUnitResults: false
  displayName: 'Build Spring Boot Backend (skip tests)'

